### PR TITLE
serial_number strip

### PR DESCRIPTION
**Pull request by kimstik**

### CODE REVIEW

**Comment by ataradov** [comment]
I don't like micro-optimization and much rather see readable code. Port opening happens once and it does not matter which case is more common. Serial numbers - same thing, it does not really matter. 

And unlike those minor changes to the code that one runs once, FIFO stuff runs all the time and the resulting code is bigger after those macros. 

I've implemented FIFO as regular functions, which results in the same code, as they get inlined. But this way everything is properly type checked.

**Comment by kimstik** [comment]
I love optimizations of any scale :) Especially if they make the code a bit more logical, clear and efficient.
It is strange that in my case the FIFO code has become not only more clear but also more compact. 
Let's call it a matter of taste. Sorry if I distracted you..

I have no idea about reason of wasting memory by uin16_t in fifo_buffer_t. 9 bit transfer provision?

Another point is 64-bit timeouts without overflow control (which will never happen?), where atomic 8/32 should be well enough.
It seems the uart timeouts approach itself is broken. rx_task with a actual implementation (64 octets, 10ms) may create a useless latency of up to 0.64s.

Obviously, all this matters if there is someone interested in it.
Thanks for the project anyway! Somehow it works.

**Comment by ataradov** [comment]
FIFO also stores parity/framing/overflow errors in the higher byte.

There is no overflow control on 64 bit numbers  because device would physically degrade faster than it would overflow. I'm not going to debate 32 bit timers, I will never use them in my life.

Timeout - I agree, it should only be reset on the first byte in the buffer. I'll fix that next time I'm doing something with the code. Ideally the first byte could be sent right away, but that would require more buffer management and I don't really care to do that.

**Comment by kimstik** [comment]
> FIFO also stores parity/framing/overflow errors in the higher byte.
> 
> There is no overflow control on 64 bit numbers because device would physically degrade faster than it would overflow. I'm not going to debate 32 bit timers, I will never use them in my life.
> 
> Timeout - I agree, it should only be reset on the first byte in the buffer. I'll fix that next time I'm doing something with the code. Ideally the first byte could be sent right away, but that would require more buffer management and I don't really care to do that.

just set timeout if buffer is empty. it will ensure 10mS latency for all received bytes without any complexity.

**Pull request closed without merging**
